### ISSUE TITLE
click on item into cart

### ISSUE THREAD

**Issue by barrycumbie** [nicolereilly/mobile-ordering#28]

**Comment by barrycumbie** [comment]
https://codepen.io/barrycumbie/pen/vYVyjZg?editors=1111

**Comment by barrycumbie** [comment]
Cool. 

@nicolereilly @katherynisabell 

You get my CNVS inbox msg?

**Comment by nicolereilly** [comment]
@barrycumbie @katherynisabell 
Yes, have been home all weekend! I will respond this afternoon!
