### ISSUE TITLE
load menu items from mongo

### ISSUE THREAD

**Issue by barrycumbie** [nicolereilly/mobile-ordering#33]
replace hard code w/db read stuff 

@barrycumbie gonna do totally new `endpoint` and `view` so as to not interfere with current `app`

**Comment by barrycumbie** [comment]
@nicolereilly @lane30schmidt @lane30schmidt got working what we chatted about on Tuesday....

... took me awhile ... a lot of syntax and typo errors. 

One remaining issue is that it doesn't group well by menu item, but that has several potential fixes. 

1) your stylesheet was killing it so I removed it. 
2) to view, have to type in `... /order` endpoint directly 
3) connects to my mongoDb, will need my `.env` secret or make your own...now, might wanna next items under category. Let's chat. 


<img width="1078" alt="Screen Shot 2023-04-27 at 10 18 32 AM" src="https://user-images.githubusercontent.com/22795694/234910114-cf251263-405b-4713-80a9-231e528bc347.png">

**Comment by nicolereilly** [comment]
> @nicolereilly @lane30schmidt @lane30schmidt got working what we chatted about on Tuesday....
> 
> ... took me awhile ... a lot of syntax and typo errors.
> 
> One remaining issue is that it doesn't group well by menu item, but that has several potential fixes.
> 
> 1. your stylesheet was killing it so I removed it.
> 2. to view, have to type in `... /order` endpoint directly
> 3. connects to my mongoDb, will need my `.env` secret or make your own...now, might wanna next items under category. Let's chat.
> 
> <img alt="Screen Shot 2023-04-27 at 10 18 32 AM" width="1078" src="https://user-images.githubusercontent.com/22795694/234910114-cf251263-405b-4713-80a9-231e528bc347.png">

I have lots of ideas, Katheryn and I updated the page to use JavaScript! I was planning on coming to see you during your office hours!

**Comment by nicolereilly** [comment]
@barrycumbie 
Katheryn and I updated the page to use JavaScript! I was planning on coming to see you during your office hours!
